# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
vars = YAML.load_file 'Servifile.yml'
vars["IS_VAGRANT"] = true

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if ENV['servi_box'].to_s.empty?
        config.vm.box = "ubuntu/trusty64"
        config.vm.box_url = "https://vagrantcloud.com/ubuntu/trusty64"
    else
        # 'servi_box' environment variable is not empty
        # This is set by 'servi usebox'.
        print "**************************\n"
        print "Using servi_box: "+ENV['servi_box']
        print "\n**************************\n\n"
        config.vm.box = ENV['servi_box']
    end

    config.vm.hostname = vars["HOST_NAME"]

    # Static ip. Add to /etc/hosts to assign a name (like xxx.dev)
    config.vm.network "private_network", ip: vars["STATIC_IP"]

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end


    # File sharing - point to my development folder
    config.vm.synced_folder "apache_config/sites-available", "/etc/apache2/sites-available", create: true,
        owner: vars["WEBDEV_UID"], group: vars["WEBDEV_GID"], mount_options: ["dmode=775","fmode=664"]
    config.vm.synced_folder vars["LOCAL_DIR"], "/var/www/#{vars['SITE_SUFFIX']}", create: true,
        owner: vars["WEBDEV_UID"], group: vars["WEBDEV_GID"], mount_options: ["dmode=775","fmode=664"]

    # Run ansible with ansible_config/playbook.yml
    config.vm.provision "ansible" do |ansible|
        ansible.inventory_path = "ansible_config/vagrant_inventory"

        ansible.extra_vars = {
            IS_VAGRANT: true,
            SYS_TYPE: "virtual_machine",
        }
        ansible.playbook = "ansible_config/playbook.yml"
        # ansible.verbose = "vvvv"
    end

end
