---


#
# Install packages
#

-   apt: update_cache=yes cache_valid_time=86400

-   name: apt - install multiple packages
    apt: pkg={{ item }} state=latest
    with_items:
      - python
      - python-pip
      - python-dev
      - python-virtualenv
      - python3
      - python3-pip
      - apache2
      - libapache2-mod-wsgi
      - libapache2-mod-macro
      - zsh

- debug: msg="**** FIX AUTOREMOVE - getting hung up somewhere? *****"
#-   name: Apt -  Autoremove unused packages  # Not sure why these are here?
#    shell: apt-get autoremove

#
# Set up admin user & group
#
-   group: name=admin state=present system=yes
-   user: name=admin comment='admin' createhome=yes shell=/usr/bin/zsh group=admin groups=adm,admin,sudo
-   authorized_key:  key="{{ lookup('file', MAIN_RSA_KEY_FILE) }}"
                     user=admin
#
# Make sure sudo & admin groups do not require passwords for sudo access
#
-   copy: dest=/etc/sudoers.d/sudo_nopasswd src=sudo_nopasswd backup=yes force=yes
-   file:  dest=/etc/sudoers.d/sudo_nopasswd mode=0440 owner=root group=root state=file
-   service: name=sudo state=restarted

#
# Set up www-data & webdev groups & users
#
-   group: name=www-data state=present system=yes
-   group: name=webdev state=present system=yes gid={{ WEBDEV_GID }}
-   user:  name=www-data
      state=present groups=www-data,webdev system=yes createhome=no
-   user:  name=webdev
      state=present group=webdev shell=/usr/bin/zsh createhome=yes uid={{ WEBDEV_UID }}

#
# Make sure apache logs & directory have proper owners / permissions
#
-   file: dest=/var/log/apache2
      owner=www-data group=www-data recurse=yes mode=775
-   file: dest={{ APACHE_LOG_DIR }}
      owner=www-data group=www-data mode=775 state=directory
-   file: dest=/etc/apache2 state=directory
      owner=webdev group=webdev recurse=yes mode=775

#
# Set apache modules & sites
#
-   command: a2enmod expires  wsgi rewrite macro
-   command: a2dissite default-ssl.conf 000-default.conf
    ignore_errors : True
-   file: path=/etc/apache2/sites-available/000-default.conf  state=absent
-   file: path=/etc/apache2/sites-available/default-ssl.conf  state=absent
-   file: path=/etc/apache2/sites-available/default           state=absent
-   file: dest=/var/www/html state=absent  # Remove default apache site


#
# Restart apache
#
-   name: Restart Apache
    service: name=apache2 state=restarted enabled=yes

#
# Turn off SSH DNS lookup
#
-   name: Turn off DNS in ssh since it causes a delay logging in on a trusty development box
    lineinfile: dest=/etc/ssh/sshd_config state=present create=yes line='UseDNS no'
-   service: name=ssh state=restarted

#
# Create local sublime command. Note you need to set up your home machine as well.
#
# http://bit.ly/1aGHLId
# http://stackoverflow.com/a/18107549/1400991
# http://stackoverflow.com/questions/18938950/rsub-with-sublime-and-ssh-connection-refusual

-   get_url: dest=/usr/local/bin/subl url=https://raw.github.com/aurora/rmate/master/rmate
-   file: state=file path=/usr/local/bin/subl mode=755


#
# Set up environment variables (/etc/environment in Ubuntu)
#


-   name:  "Make {{ PY_VENV_DIR }}"
    file: dest={{ PY_VENV_DIR }} state=directory
      owner=webdev group=webdev mode=775

-   name: "/etc/environment: Set PY_VENV_DIR = {{ PY_VENV_DIR }}"
    lineinfile: >
        dest=/etc/environment
        state=present
        line='export PY_VENV_DIR="{{ PY_VENV_DIR }}"'

-   name: "/etc/environment: Set SYS_TYPE = {{ SYS_TYPE }}"
    lineinfile: >
        dest=/etc/environment
        state=present
        line='export SYS_TYPE="{{ SYS_TYPE | default("cloud") }}"'


#
# Setup Python virtualenvs
#

-   name: Create python2 virtual environment
    command: virtualenv --python=python2.7 {{ PY_VENV_DIR }}/py2
      creates="{{ PY_VENV_DIR }}/py2"

-   file: dest="{{ PY_VENV_DIR }}/py2" state=directory recurse=yes
      owner=webdev group=webdev mode=775

-   copy: src=requirements_py2.txt dest=/tmp/requirements_py2.txt force=yes
-   name: Python2 - install base modules
    pip:
      executable: pip2
      virtualenv: "{{ PY_VENV_DIR }}/py2"
      requirements: /tmp/requirements_py2.txt

-   name: Create python3 virtual environment
    command: virtualenv --python=python3.4 {{ PY_VENV_DIR }}/py3
      creates="{{ PY_VENV_DIR }}/py3"

-   file: dest="{{ PY_VENV_DIR }}/py3" state=directory recurse=yes
      owner=webdev group=webdev mode=775

-   copy: src=requirements_py3.txt dest=/tmp/requirements_py3.txt force=yes
-   name: Python2 - install base modules
    pip:
      executable: pip3
      virtualenv: "{{ PY_VENV_DIR }}/py3"
      requirements: /tmp/requirements_py3.txt

